apiVersion: v1
kind: ConfigMap
metadata:
  name: deployk8s-env-credential
  namespace: deployk8s
data:
  DOMAIN: user-service
  USER_DOMAIN: user-service-grpc
  USER_REST_PORT: '50051'
  USER_GRPC_PORT: '50051'
  GRPC_PORT: '50051'
  DB_VENDOR: postgres
  DB_HOST: postgres-credential-service
  DB_LOGGING: "true"
  DB_PORT: '5432'
  DB_USERNAME: ${USER_DB_CREDENTIAL}
  DB_PASSWORD: ${PASS_DB_CREDENTIAL}
  NODE_ENV: production
  REST_PORT: '3000'
  JWT_PUBLIC_KEY: |
   ${JWT_PUBLIC_KEY}
  JWT_PRIVATE_KEY: |
   ${JWT_PRIVATE_KEY}

