apiVersion: v1
kind: ConfigMap
metadata:
  name: deployk8s-env-user
  namespace: deployk8s
data:
  DOMAIN: user-service
  CREDENTIAL_DOMAIN: credential-service-grpc
  CREDENTIAL_PORT: '50052'
  GRPC_PORT: '50051'
  DB_VENDOR: postgres
  DB_HOST: postgres-user-service
  DB_LOGGING: "true"
  DB_PORT: '5433'
  DB_USERNAME: ${USER_DB_USER}
  DB_PASSWORD: ${PASS_DB_USER}
  NODE_ENV: production
  REST_PORT: '3000'
  JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
