apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-credential-deployment
  namespace: deployk8s
spec:
  replicas: 1
  selector:
      matchLabels:
        app: postgres-credential-server
  template:
    metadata:
      labels:
        app: postgres-credential-server
        namespace: deployk8s
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
          - configMapRef:
              name: deployk8s-env-db-credential
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-volume
            - mountPath: /docker-entrypoint-initdb.d
              name: config
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgres-volume-credential
        - name: config
          configMap:
            name: configmap-initdb-credential
            defaultMode: 0777
            items:
            - key: script
              path: 10_postgis.sh


