apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployk8s-credential-rest
    namespace: deployk8s
    labels:
        app: deployk8s-credential-rest
spec:
    selector:
        matchLabels:
            app: deployk8s-credential-rest    
    replicas: 1
    template:
        metadata:
            namespace: deployk8s
            labels:
                app: "deployk8s-credential-rest"
            annotations:
                co.elastic.logs/json.keys_under_root: "true"
                co.elastic.logs/json.overwrite_keys: "true"
                co.elastic.logs/json.add_error_key: "true"
                co.elastic.logs/json.expand_keys: "true"
        spec:
            containers:
            - name: deployk8s-credential-rest
              image: "ghcr.io/fvsystem/fvshop-identity-express-sequelize:0.2.12"
              envFrom:
                - configMapRef:
                    name: deployk8s-env-credential
              volumeMounts:
                - mountPath: /key
                  name: configmap-keys
              # livenessProbe:
              #   httpGet:
              #       path: /health
              #       port: 3000
              #   periodSeconds: 5
              #   failureThreshold: 1
              #   timeoutSeconds: 1
              #   successThreshold: 1
              # startupProbe:
              #   httpGet:
              #       path: /health
              #       port: 3000
              #   periodSeconds: 7
              #   failureThreshold: 30
              resources:
                requests: 
                    cpu: "0.1"
                    memory: 100Mi
                limits:
                    cpu: "0.4"
                    memory: 800Mi
              # readinessProbe:
              #   httpGet:
              #       path: /health
              #       port: 3000
              #   periodSeconds: 3
              #   failureThreshold: 1
            volumes:
            - name: configmap-keys
              configMap:
                name: configmap-keys
                items:
                - key: public-key
                  path: key.public
                - key: private-key
                  path: key.private