apiVersion: v1
kind: Service
metadata:
  name: postgres-credential-service
  namespace: deployk8s
spec:
  type: LoadBalancer
  selector:
    app: postgres-credential-server
  ports:
  - port: 5432
    targetPort: 5432