apiVersion: v1
kind: Service
metadata:
  name: user-service-rest
  namespace: deployk8s
spec:
  type: LoadBalancer
  selector:
    app: deployk8s-user-rest
  ports:
  - port: 3000
    targetPort: 3000