apiVersion: v1
kind: Service
metadata:
  name: postgres-user-service
  namespace: deployk8s
spec:
  type: LoadBalancer
  selector:
    app: postgres-user-server
  ports:
  - port: 5433
    targetPort: 5432
    