apiVersion: v1
kind: Service
metadata:
  name: credential-service-grpc
  namespace: deployk8s
spec:
  type: LoadBalancer
  selector:
    app: deployk8s-credential-grpc
  ports:
  - port: 50052
    targetPort: 50051