apiVersion: v1
kind: Service
metadata:
  name: user-service-grpc
  namespace: deployk8s
spec:
  type: LoadBalancer
  selector:
    app: deployk8s-user-grpc
  ports:
  - port: 50051
    targetPort: 50051