apiVersion: v1
kind: Service
metadata:
  name: credential-service-rest
  namespace: deployk8s
spec:
  type: LoadBalancer
  selector:
    app: deployk8s-credential-rest
  ports:
  - port: 3001
    targetPort: 3000